	include	"msx.inc"

	PUBLIC	GETIME

;GETIME	- READ ELAPSED-TIME CLOCK.
;  	  OUTPUTS: DEHL = ELAPSED TIME (CENTISECONDS)
; 	  DESTROYS: A,D,E,H,L,F
GETIME:
	LD	HL, IDBYT1
	LD	A, (EXPTBL)		; MAIN ROM SLOT
	CALL	RDSLT
	EI

	AND	$80			; ARE WE RUNNING AT 60HZ?
	JR	Z, GETTIME60		; YES

	LD	HL, (JIFFY)		; DEHL = (JIFFY), 16BIT UPCONVERTED TO 32BIT
	LD	DE, 0

	SLA	L			; MULTIPLE BY 2
	RL	H
	RL	E
	RL	D

	RET

GETTIME60:
	LD	DE, 0
	LD	BC, 0
	EXX
	LD	DE, (JIFFY)
	LD	BC, 13653 		; 100 * 8192 / 60
	CALL	MUL32BIT 		; H'L'HL = (JIFFY * 100 * 8192) / 60
	CALL	DIV8192 		; DEHL = (JIFFY * 100 * 8192) / 60 / 8192
	RET				; DEHL = CENTISECONDS

DIV8192:
	LD	A, H
	EXX
	LD	B, 5

DIV8192_1:
	SRL	H
	RR	L
	RR	A
	DJNZ	DIV8192_1

	LD 	D, 0
	LD 	E, H
	LD 	H, L
	LD 	L, A
	RET


;==================================================
; MULTIPLY ROUTINE 32*32BIT=32BIT
; H"L"HL = B"C"BC * D"E"DE
; NEEDS REGISTER A, CHANGES FLAGS
;
MUL32BIT:
	AND	A 			; RESET CARRY FLAG
	SBC	HL, HL			; LOWER RESULT = 0
	EXX
	SBC	HL, HL			; HIGHER RESULT = 0
	LD	A, B			; MPR IS AC'BC
	LD	B, 32			; INITIALIZE LOOP COUNTER
MUL32LOOP:
	SRA 	A			; RIGHT SHIFT MPR
	RR	C
	EXX
	RR	B
	RR	C			; LOWEST BIT INTO CARRY
	JR	NC, MUL32NOADD
	ADD	HL, DE			; RESULT += MPD
	EXX
	ADC	HL, DE
	EXX

MUL32NOADD:
	SLA	E 			; LEFT SHIFT MPD
	RL	D
	EXX
	RL	E
	RL	D
	DJNZ	MUL32LOOP
	EXX
	RET
